apiVersion: v1
data:
  mapRoles: |
    - groups:
      - system:masters
      rolearn: arn:aws:iam::835891498682:role/UdacityFlaskDeployCBKubectlRole
      username: build  
    - groups:
      - system:bootstrappers
      - system:nodes
      rolearn: arn:aws:iam::835891498682:role/eksctl-simple-jwt-api-nodegroup-n-NodeInstanceRole-1KYWXQSAXAW2K
      username: system:node:{{EC2PrivateDNSName}}
kind: ConfigMap
metadata:
  creationTimestamp: "2022-10-13T17:20:22Z"
  name: aws-auth
  namespace: kube-system
  resourceVersion: "1637"
  uid: 32cb2da5-097a-4f85-bb9f-eddc6670f211
